# This is a TOML document.

title = "48v Charger configuration"

[uarts]
uart0 = { phy = 0, dev = "/dev/ttyUSB3"}
uart1 = { phy = 0, dev = "/dev/ttyUSB4"}
uart2 = { phy = 1, dev = "/dev/ttyUSB5"}
uart3 = { phy = 1, dev = "/dev/ttyUSB6"}
