# This is a TOML document.

title = "48v Charger configuration"

[uarts]
uart0 = { phy = 0, dev = "/dev/ttyUSB0"}
uart1 = { phy = 0, dev = "/dev/ttyUSB1"}
uart2 = { phy = 1, dev = "/dev/ttyUSB2"}
uart3 = { phy = 1, dev = "/dev/ttyUSB3"}

[address]
control = 'a'

[command]

  [command.set_voltage]
  cmd = 'wu'
  min = 0
  max = 6000
  scale = 100
  format = '{:04d}'
  regex = 'ok'

  [command.set_current]
  cmd = 'wi'
  min = 0
  max = 1200
  scale = 100
  format = '{:04d}'
  regex = 'ok'

  [command.set_output]
  cmd = 'wo'
  min = 0
  max = 1
  scale = 1
  format = '{:d}'
  regex = 'ok'

  [command.set_auto_output]
  cmd = 'wy'
  min = 0
  max = 1
  scale = 1
  format = '{:d}'
  regex = 'ok'

  [command.read_actual_voltage]
  cmd = 'ru'
  scale = 100
  format = false
  regex = '\d{11}'

  [command.read_actual_current]
  cmd = 'ri'
  scale = 100
  format = false
  regex = '\d{11}'

  [command.read_actual_working_time]
  cmd = 'rt'
  scale = 1
  format = false
  regex = '\d{11}'

  [command.read_actual_output_capacity]
  cmd = 'rc'
  scale = 100
  format = false
  regex = '\d{11}'

  [command.read_set_voltage]
  cmd = 'rv'
  scale = 100
  format = false
  regex = '\d{11}'

  [command.read_set_current]
  cmd = 'ra'
  scale = 100
  format = false
  regex = '\d{11}'

  [command.read_output_state]
  cmd = 'ro'
  scale = 1
  format = false
  regex = '\d{11}'
