# This is a TOML document.

title = "48v Charger configuration"

[temperature]
base_path = '/sys/bus/w1/devices'
sub_path = '' # '/hwmon/hwmon3'
temp_file = 'w1_slave' # 'temp1_input'

[temperature_regex]
line0 = '([0-9a-f]{2}\s){9}:\scrc=[0-9a-f]{2}\sYES'
line1 = '([0-9a-f]{2}\s){9}t=\d{5}'
prefix = '([0-9a-f]{2}\s){9}t='

[temperature_devices]
temp0 = { id = 0, phy = 0, dev = "28-00000a91c123"}
temp1 = { id = 1, phy = 0, dev = "28-00000a92406c"}
temp2 = { id = 2, phy = 1, dev = "28-00000a930dc2"}
temp3 = { id = 3, phy = 2, dev = "28-00000b1f4fd4"}

[uart]
baudrate = 4800
bytesize = 8
parity = 'N'
stopbits = 1
timeout = 0

[uarts]
uart0 = { id = 0, phy = 0, dev = "/dev/ttyUSB2"}
uart1 = { id = 1, phy = 0, dev = "/dev/ttyUSB4"}
# uart2 = { id = 2, phy = 1, dev = "/dev/ttyUSB3"}
# uart3 = { id = 3, phy = 1, dev = "/dev/ttyUSB5"}

[mqtt]
client = '48vCharger_py'
host = 'inverterpi'
topic = '48vChargerxx'

[command]
  [command.'Default']
  prefix = 'a'
  reply_prefix = '#'
  suffix = "\r\n"
  cmd_format = '{!s}'
  encoding_base = 10

  [command.set_voltage]
  cmd = 'wu'
  value = 12
  range = {scale = 0.01, min = 0, max = 60.00}
  send_value_format = '{:04d}'
  reply_regex = 'ok'

  [command.set_current]
  cmd = 'wi'
  value = 2
  range = {scale = 0.01, min = 0, max = 12.00}
  send_value_format = '{:04d}'
  reply_regex = 'ok'

  [command.set_output]
  cmd = 'wo'
  range = {scale = 1, min = 0, max = 1}
  send_value_format = '{:d}'
  reply_regex = 'ok'

  [command.set_auto_output]
  cmd = 'wy'
  range = {scale = 1, min = 0, max = 1}
  send_value_format = '{:d}'
  reply_regex = 'ok'

  [command.read_actual_voltage]
  cmd = 'ru'
  range = {scale = 0.01, min = 0, max = 100.00}
  reply_regex = '\d{11}'

  [command.read_actual_current]
  cmd = 'ri'
  range = {scale = 0.01, min = 0, max = 100.00}
  reply_regex = '\d{11}'

  [command.read_actual_working_time]
  cmd = 'rt'
  range = {scale = 1, min = 0, max = 9.999e+10}
  reply_regex = '\d{11}'

  [command.read_actual_output_capacity]
  cmd = 'rc'
  range = {scale = 0.01, min = 0, max = 9.999e+8}
  reply_regex = '\d{11}'

  [command.read_set_voltage]
  cmd = 'rv'
  range = {scale = 100, min = 0, max = 60.00}
  reply_regex = '\d{11}'

  [command.read_set_current]
  cmd = 'ra'
  range = {scale = 100, min = 0, max = 12.00}
  reply_regex = '\d{11}'

  [command.read_output_state]
  cmd = 'ro'
  range = {scale = 1, min = 0, max = 1}
  reply_regex = '\d{11}'
