title = "BMS Controler configuration"

[uart]
baudrate = 9600
bytesize = 8
parity = 'E'
stopbits = 1
timeout = 0.1

[uarts]
uart0 = {dev = '/dev/ttyUSB1', phy = 0}

[mqtt]
client = 'BMS_py'
host = 'inverterpi'
topic = 'BMSxx'


[command]

  [command.'Default']
  single_uart = true
  prefix = ':'
  reply_prefix = ':'
  mode = 0x22
  suffix = "\n"
  cmd_format = '{:04X}'
  encoding_base = 16
  value_reply = true
  reply_regex = '[0-9A-F]'

  [command.'Relays Status']
  cmd = 0xF004
  payload = {bytes = 1, encode = 2, signed = false}
  range = {scale =1, min = 0, max = 255}
  Lookup_Table =[{mask = 0x01, name = 'Discharge Enable'},
                {mask = 0x02, name = 'Charge Enable'},
                {mask = 0x04, name = 'Charger Safety'},
                {mask = 0x08, name = 'Errors Present'},
                {mask = 0x10, name = 'Multi-purpose Input'},
                {mask = 0x20, name = 'AM Power'},
                {mask = 0x40, name = 'Ready Power'},
                {mask = 0x80, name = 'Charge Power'}]

  [command.'Populated Cell Count']
  cmd = 0xF007
  payload = {bytes = 1, encode = 1, signed = false}
  range = {scale =1, min = 0, max = 255}

  [command.'Pack Charge Current Limit']
  cmd = 0xF00A
  payload = {bytes = 1, encode = 2, signed = false}
  range = {scale =1, min = 0, max = 500}

  [command.'Pack Disharge Current Limit']
  cmd = 0xF00B
  payload = {bytes = 1, encode = 2, signed = false}
  range = {scale =1, min = 0, max = 500}

  [command.'Signed Pack Current']
  cmd = 0xF00C
  payload = {bytes = 1, encode = 2, signed = true}
  range = {scale =0.1, min = -500, max = 500}

  [command.'Pack Voltage']
  cmd = 0xF00D
  payload = {bytes = 1, encode = 2, signed = false}
  range = {scale =0.1, min = 0, max = 350}

  [command.'Pack Open Voltage']
  cmd = 0xF00E
  payload = {bytes = 1, encode = 2, signed = false}
  range = {scale =0.1, min = 0, max = 350}

  [command.'Pack State of Charge']
  cmd = 0xF00F
  payload = {bytes = 1, encode = 1, signed = false}
  range = {scale =0.5, min = 0, max = 100}

  [command.'Pack Amphours']
  cmd = 0xF010
  payload = {bytes = 1, encode = 2, signed = false}
  range = {scale =0.1, min = 0, max = 6535.5}

  [command.'Pack Resistance']
  cmd = 0xF011
  payload = {bytes = 1, encode = 2, signed = false}
  range = {scale =0.01, min = 0, max = 255}

  [command.'Pack Depth of Discharge']
  cmd = 0xF012
  payload = {bytes = 1, encode = 1, signed = false}
  range = {scale = 0.5, min = 0, max = 100}

  [command.'Pack Health']
  cmd = 0xF013
  payload = {bytes = 1, encode = 1, signed = false}
  range = {scale =1, min = 0, max = 100}

  [command.'Pack Summed Voltage']
  cmd = 0xF014
  payload = {bytes = 1, encode = 2, signed = false}
  range = {scale =0.01, min = 0, max = 350}

  [command.'Total Pack Cycles']
  cmd = 0xF015
  payload = {bytes = 1, encode = 2, signed = false}
  range = {scale =1, min = 0, max = 65535}

  [command.'Lowest Cell Voltage']
  cmd = 0xF032
  payload = {bytes = 1, encode = 2, signed = false}
  range = {scale =0.0001, min = 0, max = 5}

  [command.'Highest Cell Voltage']
  cmd = 0xF033
  payload = {bytes = 1, encode = 2, signed = false}
  range = {scale =0.0001, min = 0, max = 5}

  [command.'Raw Temperature']
  cmd = 0xF0FF
  payload = {bytes = 3, encode = 1, signed = true}
  range = {scale =1, min = -40, max = 80}
  span = [1, 3]

  [command.'Cell Voltages']
  cmds = [0xF100, 0xF101]
  payload = {bytes = 12, encode = 2, signed = false}
  range = {scale =0.0001, min = 0, max = 5}
  spans = {0xF100 = [1, 12], 0xF101 = [13, 16]}

  [command.'Internal Resistances']
  cmds = [0xF200, 0xF201]
  payload = {bytes = 12, encode = 2, signed = false}
  range = {scale =0.0001, min = 0, max = 5}
  spans = {0xF200 = [1, 12], 0xF201 = [13, 16]}

  [command.'Open Cell Voltages']
  cmds = [0xF300, 0xF301]
  payload = {bytes = 12, encode = 2, signed = false}
  range = {scale =0.01, min = 0, max = 327.67}
  spans = {0xF300 = [1, 12], 0xF301 = [13, 16]}
